#!/usr/bin/env bash
set -e
oldrev=$1
newrev=$2

echo files changed: $(git diff $oldrev $newrev --diff-filter=ACDMR --name-only | wc -l)

umask 002

git submodule sync && git submodule update --init --recursive

./bin/setup

supervisorctl restart store-rest
supervisorctl restart store-ws
supervisorctl restart async-convert
supervisorctl restart ploy

